#!/usr/bin/env python

import argparse
import subprocess

parser = argparse.ArgumentParser(description='Customize the integration')
parser.add_argument('-n', '--name', required=True, metavar='framework_name', type=str, help='Name of the framework.')
parser.add_argument('-g', '--git', required=True, metavar='git_repo_URL', type=str, help='Repo URL.')
parser.add_argument('-v', '--major', required=True, metavar='major_version_number', type=int, help='Major Version.')

args = parser.parse_args()

def search_replace(old, new):
    for f in subprocess.check_output(['grep', '-rIl', old, '.']).split():
        if f.endswith('customize'):
            continue
        subprocess.call(['sed', "-i", '', 's/{}/{}/g'.format(old, new), f])

search_replace('__FRAMEWORKNAME__', args.name)
search_replace('__GITREPO__', args.git.replace('/', '\\/'))
search_replace('__MAJORVERSION__', str(args.major))

